spring:
  config:
    activate:
      on-profile: staging

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  cache:
    type: caffeine

# Logging for staging
logging:
  level:
    org.springframework.security: INFO
    com.quyen.shoplite: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
